import { defineConfig } from 'vite-plus'

export default defineConfig({
  fmt: {
    printWidth: 120,
    tabWidth: 2,
    useTabs: false,

    // Reduce syntax noise and token count.
    semi: false,
    singleQuote: true,
    jsxSingleQuote: false,
    quoteProps: 'as-needed',
    trailingComma: 'all',

    // Keep JSX/TSX more compact and easier for agents to rewrite.
    arrowParens: 'avoid',
    bracketSpacing: true,
    bracketSameLine: false,
    singleAttributePerLine: false,

    // Better for diff stability and generated code consistency.
    endOfLine: 'lf',
    embeddedLanguageFormatting: 'auto',
    htmlWhitespaceSensitivity: 'css',
    proseWrap: 'preserve',

    // Avoid pragma noise.
    insertPragma: false,
    requirePragma: false,

    // Sorting improves deterministic generation and merge quality.
    sortPackageJson: true,
    sortTailwindcss: true,

    // Remove obsolete / unnecessary defaults.
    ignorePatterns: [
      // Dependencies
      'node_modules',
      '.pnp',
      '.pnp.js',

      // Build output
      '.next',
      'out',
      'build',
      'coverage',
      '.turbo',
      '.vercel',

      // Python
      '.venv',
      '__pycache__',
      '*.py[cod]',
      '.ruff_cache',

      // Logs & env
      '.env*',
      '*.log',
      'npm-debug.log*',

      // OS / editor
      '.DS_Store',
      '.vscode',

      // Infra
      '.flyio',
      'fly.toml',

      // Generated files
      'next-env.d.ts',
      'lib/api/generated/**',

      // Secrets
      '*.pem',
    ],
  },
  lint: {
    categories: {
      correctness: 'error',
      nursery: 'warn',
      pedantic: 'off',
      perf: 'error',
      restriction: 'warn',
      style: 'warn',
      suspicious: 'error',
    },
    env: {
      builtin: true,
      browser: true,
      es2024: true,
      node: true,
    },
    globals: {},
    ignorePatterns: [
      '.git/',
      '**/*.d.ts',
      '**/*.test.ts',
      '**/*.test.tsx',
      'src/tests/',
      '**/*.js',
      '**/*.mjs',
      '**/cdk.out/',
      '**/dist/',
      '**/node_modules/',
      '**/bp_modules/',
      '**/.botpress/',
      '**/gen/',
      '**/.turbo/',
      '**/.genenv/',
      'lib/api/generated/schema.ts',
      'e2e/',
      'scripts/',
      'playwright.config.ts',
      'eslint.config.*',
      'src/components/providers/session-provider.tsx',
      'src/features/assessments/registry/code-challenge/hooks.ts',
      'src/features/assessments/shell/AssessmentLayout.tsx',
      'src/features/assessments/registry/code-challenge/hooks.ts',
      'src/components/Security/HeaderProfileBox.tsx',
      'src/features/assessments/studio/NativeItemStudio.tsx',
      'src/services/gamification/server.ts',
      'src/lib/api/generated/schema.ts',
    ],
    plugins: [
      'import',
      'jsdoc',
      'jsx-a11y',
      'nextjs',
      'node',
      'oxc',
      'promise',
      'react',
      'react-perf',
      'typescript',
      'unicorn',
    ],
    rules: {
      'react/react-compiler': 'off',
      'no-shadow': 'warn',
      'typescript/no-explicit-any': 'warn',
      'prefer-named-capture-group': 'off',
      'arrow-body-style': 'off',
      'capitalized-comments': 'off',
      complexity: 'off',
      curly: 'off',
      'default-case': 'off',
      'func-style': 'off',
      'id-length': 'off',
      'init-declarations': 'off',
      'max-lines': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'new-cap': 'off',
      'no-await-in-loop': 'off',
      'no-console': 'off',
      'no-constant-condition': 'off',
      'no-debugger': 'off',
      'no-duplicate-imports': 'off',
      'no-empty-function': 'off',
      'no-empty-pattern': 'off',
      'no-implicit-coercion': 'off',
      'no-magic-numbers': 'off',
      'no-nested-ternary': 'off',
      'no-null': 'off',
      'no-relative-parent-imports': 'off',
      'no-ternary': 'off',
      'no-undefined': 'off',
      'no-use-before-define': 'off',
      'no-var': 'off',
      'no-void': 'off',
      'prefer-template': 'off',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'vars-on-top': 'off',
      yoda: 'off',
      'no-optional-chaining': 'off',
      'no-rest-spread-properties': 'off',
      'class-methods-use-this': 'off',
      'no-unreachable': 'error',
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      'no-extra-boolean-cast': 'error',
      'no-regex-spaces': 'error',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-rename': 'error',
      'object-shorthand': 'error',
      'oxc/no-async-await': 'off',
      'import/no-default-export': 'off',
      'import/no-named-export': 'off',
      'import/no-unassigned-import': 'off',
      'import/prefer-default-export': 'off',
      'import/group-exports': 'off',
      'import/exports-last': 'off',
      'import/no-namespace': 'off',
      'import/no-duplicates': 'error',
      'import/no-self-import': 'error',
      'import/no-named-as-default': 'off',
      'typescript/consistent-type-imports': [
        'error',
        {
          prefer: 'type-imports',
          fixStyle: 'inline-type-imports',
        },
      ],
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-unused-vars': 'off',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/explicit-function-return-type': 'off',
      'typescript/explicit-module-boundary-types': 'off',
      'typescript/no-floating-promises': 'off',
      'typescript/no-misused-promises': 'off',
      'typescript/no-unnecessary-condition': 'off',
      'typescript/no-unsafe-type-assertion': 'off',
      'typescript/prefer-readonly-parameter-types': 'off',
      'typescript/promise-function-async': 'off',
      'typescript/strict-void-return': 'off',
      'typescript/consistent-return': 'off',
      'typescript/no-base-to-string': 'off',
      'typescript/restrict-template-expressions': 'off',
      'typescript/no-redundant-type-constituents': 'off',
      'typescript/no-unsafe-enum-comparison': 'off',
      'typescript/no-misused-spread': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/button-has-type': 'off',
      'react/iframe-missing-sandbox': 'off',
      'react/jsx-filename-extension': 'off',
      'react/jsx-handler-names': 'off',
      'react/jsx-max-depth': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/no-array-index-key': 'off',
      'react/no-clone-element': 'off',
      'react/no-danger': 'off',
      'react/no-multi-comp': 'off',
      'react/no-react-children': 'off',
      'react/only-export-components': 'off',
      'react/forbid-component-props': 'off',
      'react/no-unstable-nested-components': [
        'error',
        {
          allowAsProps: true,
        },
      ],
      'react-perf/jsx-no-new-array-as-prop': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      'react-perf/jsx-no-new-object-as-prop': 'off',
      'react-perf/jsx-no-jsx-as-prop': 'off',
      'promise/prefer-await-to-callbacks': 'off',
      'promise/prefer-await-to-then': 'off',
      'promise/no-promise-in-callback': 'off',
      'promise/avoid-new': 'off',
      'unicorn/filename-case': 'off',
      'unicorn/no-array-reduce': 'off',
      'unicorn/no-nested-ternary': 'off',
      'unicorn/no-null': 'off',
      'unicorn/prefer-string-raw': 'off',
      'unicorn/prefer-array-find': 'error',
      'unicorn/prefer-export-from': 'off',
      'unicorn/prefer-includes': 'error',
      'unicorn/number-literal-case': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'jsx-a11y/prefer-tag-over-role': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/control-has-associated-label': 'off',
      'jsx-a11y/media-has-caption': 'off',
      'no-underscore-dangle': 'off',
      'nextjs/no-assign-module-variable': 'off',
      'jsdoc/check-tag-names': 'off',
      'typescript/no-non-null-assertion': 'off',
      'unicorn/no-array-for-each': 'off',
      'node/no-process-env': 'off',
      'prefer-destructuring': 'off',
      'no-continue': 'off',
      'react/hook-use-state': 'off',
      'unicorn/no-await-expression-member': 'off',
      'no-bitwise': 'off',
      'typescript/no-invalid-void-type': 'off',
      'unicorn/no-document-cookie': 'off',
      'oxc/no-barrel-file': 'off',
      'unicorn/prefer-ternary': 'off',
      'typescript/no-dynamic-delete': 'off',
      'default-param-last': 'off',
      'no-param-reassign': 'off',
      'promise/param-names': 'off',
      'promise/no-nesting': 'off',
      'import/first': 'off',
      'vite-plus/prefer-vite-plus-imports': 'error',
      'react/jsx-no-literals': [
        'warn',
        {
          noStrings: true,
          allowedStrings: [
            '•',
            '—',
            '×',
            '✓',
            '🛠️',
            '🏆',
            '🎉',
            'XP',
            '+',
            ':',
            '/',
            '%',
            '@',
            '(',
            ')',
            '#',
            '{',
            '}',
            '.',
            '·',
            '*',
            '-',
            ',',
            '→',
            '←',
            '✨',
            '⭐',
            '⚠',
            '...',
            '…',
            '|',
            'KB',
            'MB',
            'JSON',
            'CSV',
            '🖼',
            '"',
            'D',
            '1',
            '\\frac{',
            '\\sqrt{x}',
            '\\sum_{',
            '\\int_{',
            'x^{',
            'x_{',
            '^',
          ],
          ignoreProps: true,
        },
      ],
    },
    settings: {},
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
})
