"""Typed AI runtime contracts shared by agents, orchestration, and API routes."""

from src.services.ai.contracts.events import (
    ArtifactDeltaPayload,
    CitationAddedPayload,
    MessageDeltaPayload,
    RunErrorPayload,
    StatusChangedPayload,
    ToolProgressPayload,
    V2ArtifactDeltaEvent,
    V2CitationAddedEvent,
    V2MessageDeltaEvent,
    V2RunAbortedEvent,
    V2RunErrorEvent,
    V2RunFinishedEvent,
    V2RunStartedEvent,
    V2StatusChangedEvent,
    V2ToolDeltaEvent,
    V2ToolFinishedEvent,
    V2ToolStartedEvent,
)
from src.services.ai.contracts.intents import AIIntent, normalize_ai_intent
from src.services.ai.contracts.outputs import (
    AIArtifact,
    ArtifactKind,
    AuthoringPatch,
    CodeReviewHint,
    EvidenceCitation,
    Flashcard,
    FlashcardSet,
    HintLadder,
    HintStep,
    RubricFeedbackExplanation,
    SafetyRefusal,
    TeacherInterventionDraft,
    TutorAnswer,
    build_artifact_for_intent,
)

__all__ = [
    "AIArtifact",
    "AIIntent",
    "ArtifactDeltaPayload",
    "ArtifactKind",
    "AuthoringPatch",
    "CitationAddedPayload",
    "CodeReviewHint",
    "EvidenceCitation",
    "Flashcard",
    "FlashcardSet",
    "HintLadder",
    "HintStep",
    "MessageDeltaPayload",
    "RubricFeedbackExplanation",
    "RunErrorPayload",
    "SafetyRefusal",
    "StatusChangedPayload",
    "TeacherInterventionDraft",
    "ToolProgressPayload",
    "TutorAnswer",
    "V2ArtifactDeltaEvent",
    "V2CitationAddedEvent",
    "V2MessageDeltaEvent",
    "V2RunAbortedEvent",
    "V2RunErrorEvent",
    "V2RunFinishedEvent",
    "V2RunStartedEvent",
    "V2StatusChangedEvent",
    "V2ToolDeltaEvent",
    "V2ToolFinishedEvent",
    "V2ToolStartedEvent",
    "build_artifact_for_intent",
    "normalize_ai_intent",
]
