import type {
  ActivityDropoffRow,
  AdminAnalyticsResponse,
  AlertItem,
  AnalyticsDataQuality,
  AnomalyItem,
  AssessmentAuditEventRow,
  AssessmentCohortRow,
  AssessmentDiagnosticsSnapshot,
  AssessmentItemAnalyticsRow,
  AssessmentLearnerRow,
  AssessmentOutlierRow,
  AssessmentSloSnapshot,
  AssessmentSupportAlertRow,
  AssessmentSupportDiagnostics,
  AtRiskLearnerRow,
  AtRiskLearnersResponse,
  CommonFailureRow,
  ContentBottleneckRow,
  ContentHealthRow,
  DrillThroughResponse,
  FilterOption,
  ForecastItem,
  FunnelStep,
  GradingBacklogItem,
  HistogramBucket,
  InsightFeedItem,
  MetricCard,
  QuestionDifficultyRow,
  RiskDistributionCounts,
  SaveViewRequest,
  SavedView,
  SavedViewList,
  TeacherAssessmentDetailResponse,
  TeacherAssessmentListResponse,
  TeacherCourseDetailResponse,
  TeacherCourseListResponse,
  TeacherCourseRow,
  TeacherOverviewParams,
  TeacherOverviewResponse,
  TeacherWorkloadSummary,
  TimeSeriesPoint,
} from '@/lib/api/generated/zod'

export type AnalyticsQuery = TeacherOverviewParams
export type WindowPreset = NonNullable<TeacherOverviewParams['window']>
export type ComparePreset = NonNullable<TeacherOverviewParams['compare']>
export type Bucket = NonNullable<TeacherOverviewParams['bucket']>
export type SortOrder = NonNullable<TeacherOverviewParams['sort_order']>
export type AssessmentType = AssessmentOutlierRow['assessment_type']

export type AnalyticsFilterOption = FilterOption
export type SavedAnalyticsViewCreate = SaveViewRequest
export type SavedAnalyticsViewListResponse = SavedViewList
export type SavedAnalyticsViewRow = SavedView
export type AssessmentMigrationStatus = string

export type {
  ActivityDropoffRow,
  AdminAnalyticsResponse,
  AlertItem,
  AnalyticsDataQuality,
  AnomalyItem,
  AssessmentAuditEventRow,
  AssessmentCohortRow,
  AssessmentDiagnosticsSnapshot,
  AssessmentItemAnalyticsRow,
  AssessmentLearnerRow,
  AssessmentOutlierRow,
  AssessmentSloSnapshot,
  AssessmentSupportAlertRow,
  AssessmentSupportDiagnostics,
  AtRiskLearnerRow,
  AtRiskLearnersResponse,
  CommonFailureRow,
  ContentBottleneckRow,
  ContentHealthRow,
  DrillThroughResponse,
  ForecastItem,
  FunnelStep,
  GradingBacklogItem,
  HistogramBucket,
  InsightFeedItem,
  MetricCard,
  QuestionDifficultyRow,
  RiskDistributionCounts,
  TeacherAssessmentDetailResponse,
  TeacherAssessmentListResponse,
  TeacherCourseDetailResponse,
  TeacherCourseListResponse,
  TeacherCourseRow,
  TeacherOverviewResponse,
  TeacherWorkloadSummary,
  TimeSeriesPoint,
}
