/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedHomeRouteImport } from './routes/_authed/home'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as PublicCollectionsRouteImport } from './routes/_public/collections'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const PublicCollectionsRoute = PublicCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/home': typeof AuthedHomeRoute
  '/login': typeof GuestLoginRoute
  '/collections': typeof PublicCollectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/home': typeof AuthedHomeRoute
  '/login': typeof GuestLoginRoute
  '/collections': typeof PublicCollectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/home': typeof AuthedHomeRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_public/collections': typeof PublicCollectionsRoute
  '/_guest/': typeof GuestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/login' | '/collections'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/login' | '/collections'
  id:
    | '__root__'
    | '/_authed'
    | '/_guest'
    | '/_public'
    | '/_authed/home'
    | '/_guest/login'
    | '/_public/collections'
    | '/_guest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_public/collections': {
      id: '/_public/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof PublicCollectionsRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedHomeRoute: typeof AuthedHomeRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedHomeRoute: AuthedHomeRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface PublicRouteChildren {
  PublicCollectionsRoute: typeof PublicCollectionsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCollectionsRoute: PublicCollectionsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
