from collections.abc import Iterator
from typing import TypeVar, overload

_T = TypeVar("_T")

class TTLCache[K, V]:
    def __init__(self, maxsize: int, global_ttl: float) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    @overload
    def get(self, key: K) -> V | None: ...
    @overload
    def get(self, key: K, default: _T) -> V | _T: ...
    @overload
    def pop(self, key: K) -> V: ...
    @overload
    def pop(self, key: K, default: _T) -> V | _T: ...
    def clear(self) -> None: ...
