/**
 * Embed provider registry for Ashyk Bilim LMS.
 *
 * Icon names reference named exports from `@icons-pack/react-simple-icons`.
 * Usage in a component:
 *
 *   import * as Si from '@icons-pack/react-simple-icons';
 *   const Icon = provider.iconName ? (Si as Record<string, React.ElementType>)[provider.iconName] : null;
 *   {Icon && <Icon size={16} />}
 */

export type EmbedCategoryId =
  | 'popular'
  | 'visual'
  | 'code'
  | 'media'
  | 'assessment'
  | 'productivity'
  | 'academic'
  | 'collaboration';

export interface EmbedCategory {
  id: EmbedCategoryId;
  label: string;
  description: string;
}

export const EMBED_CATEGORIES: EmbedCategory[] = [
  { id: 'popular', label: 'popularLabel', description: 'popularDescription' },
  { id: 'visual', label: 'visualLabel', description: 'visualDescription' },
  { id: 'code', label: 'codeLabel', description: 'codeDescription' },
  { id: 'media', label: 'mediaLabel', description: 'mediaDescription' },
  { id: 'assessment', label: 'assessmentLabel', description: 'assessmentDescription' },
  { id: 'productivity', label: 'productivityLabel', description: 'productivityDescription' },
  { id: 'academic', label: 'academicLabel', description: 'academicDescription' },
  { id: 'collaboration', label: 'collaborationLabel', description: 'collaborationDescription' },
];

export interface EmbedProvider {
  type: string;
  label: string;
  categories: readonly EmbedCategoryId[];
  description: string;
  placeholder: string;
  hostnames: readonly string[];
  defaultHeight: number;
  allow?: string;
  requiresEmbedUrl?: boolean;
  /** Named export from `@icons-pack/react-simple-icons`, e.g. `'SiYoutube'`. */
  iconName?: string;
}

export const EMBED_PROVIDERS = [
  // ─── VISUAL ──────────────────────────────────────────────────────────────────
  {
    type: 'excalidraw',
    label: 'Excalidraw',
    categories: ['visual', 'popular'],
    description: 'Hand-drawn diagrams and brainstorming boards.',
    placeholder: 'https://excalidraw.com/#room=...',
    hostnames: ['excalidraw.com'],
    defaultHeight: 520,
    iconName: 'SiExcalidraw',
  },
  {
    type: 'tldraw',
    label: 'tldraw',
    categories: ['visual', 'popular'],
    description: 'Fast infinite canvas for sketches and visual thinking.',
    placeholder: 'https://tldraw.com/r/room-id',
    hostnames: ['tldraw.com'],
    defaultHeight: 520,
  },
  {
    type: 'figma',
    label: 'Figma',
    categories: ['visual', 'popular'],
    description: 'Live design files and clickable prototypes.',
    placeholder: 'https://www.figma.com/file/...',
    hostnames: ['figma.com', 'www.figma.com'],
    defaultHeight: 560,
    iconName: 'SiFigma',
  },
  {
    type: 'canva',
    label: 'Canva',
    categories: ['visual'],
    description: 'Posters, infographics, presentations, and design assets.',
    placeholder: 'https://www.canva.com/design/...',
    hostnames: ['canva.com', 'www.canva.com'],
    defaultHeight: 560,
    iconName: 'SiCanva',
  },
  {
    type: 'miro',
    label: 'Miro',
    categories: ['visual'],
    description: 'Collaborative workshops, mapping, and group boards.',
    placeholder: 'https://miro.com/app/board/...',
    hostnames: ['miro.com', 'www.miro.com'],
    defaultHeight: 560,
    iconName: 'SiMiro',
  },
  {
    type: 'mural',
    label: 'Mural',
    categories: ['visual'],
    description: 'Enterprise visual collaboration and workshop canvases.',
    placeholder: 'https://app.mural.co/...',
    hostnames: ['mural.co', 'app.mural.co'],
    defaultHeight: 560,
  },
  {
    type: 'spline',
    label: 'Spline',
    categories: ['visual'],
    description: 'Interactive 3D scenes and objects.',
    placeholder: 'https://my.spline.design/...',
    hostnames: ['spline.design', 'my.spline.design'],
    defaultHeight: 560,
    iconName: 'SiSpline',
  },
  {
    type: 'lottiefiles',
    label: 'LottieFiles',
    categories: ['visual'],
    description: 'Lightweight animations for explainers and feedback.',
    placeholder: 'https://lottiefiles.com/...',
    hostnames: ['lottiefiles.com', 'www.lottiefiles.com'],
    defaultHeight: 420,
    iconName: 'SiLottiefiles',
  },
  {
    type: 'sketchpad',
    label: 'Sketchpad',
    categories: ['visual'],
    description: 'Simple browser sketching canvas for quick drawings.',
    placeholder: 'https://sketchpad.app/...',
    hostnames: ['sketchpad.app', 'www.sketchpad.app'],
    defaultHeight: 520,
  },
  // NEW ↓
  {
    type: 'prezi',
    label: 'Prezi',
    categories: ['visual'],
    description: 'Zoomable, non-linear presentations for dynamic storytelling.',
    placeholder: 'https://prezi.com/view/...',
    hostnames: ['prezi.com'],
    defaultHeight: 560,
    iconName: 'SiPrezi',
  },
  {
    type: 'pitch',
    label: 'Pitch',
    categories: ['visual'],
    description: 'Collaborative slide decks with real-time co-editing.',
    placeholder: 'https://pitch.com/public/...',
    hostnames: ['pitch.com'],
    defaultHeight: 560,
    iconName: 'SiPitch',
  },
  {
    type: 'gamma',
    label: 'Gamma',
    categories: ['visual'],
    description: 'AI-generated presentations, docs, and web pages.',
    placeholder: 'https://gamma.app/public/...',
    hostnames: ['gamma.app'],
    defaultHeight: 560,
    iconName: 'SiGamma',
  },
  {
    type: 'google-slides',
    label: 'Google Slides',
    categories: ['visual', 'popular'],
    description: 'Cloud-based presentations with real-time collaboration.',
    placeholder: 'https://docs.google.com/presentation/d/.../edit',
    hostnames: ['docs.google.com'],
    defaultHeight: 560,
    iconName: 'SiGoogleslides',
  },
  {
    type: 'powerpoint',
    label: 'PowerPoint Online',
    categories: ['visual', 'popular'],
    description: 'Microsoft PowerPoint presentations for the web.',
    placeholder: 'https://onedrive.live.com/embed?resid=...',
    hostnames: ['office.com', 'microsoft.com', 'live.com'],
    defaultHeight: 560,
    iconName: 'SiMicrosoftpowerpoint',
  },
  {
    type: 'ms-whiteboard',
    label: 'Microsoft Whiteboard',
    categories: ['visual'],
    description: 'Digital canvas for collaboration and ideation.',
    placeholder: 'https://whiteboard.office.com/me/whiteboards/...',
    hostnames: ['whiteboard.office.com', 'whiteboard.microsoft.com'],
    defaultHeight: 560,
    iconName: 'SiMicrosoft',
  },
  {
    type: 'explain-everything',
    label: 'Explain Everything',
    categories: ['visual'],
    description: 'Interactive whiteboard and screen recording tool.',
    placeholder: 'https://explaineverything.com/board/...',
    hostnames: ['explaineverything.com'],
    defaultHeight: 560,
  },
  {
    type: 'slides-com',
    label: 'Slides.com',
    categories: ['visual'],
    description: 'Reveal.js-powered presentations with live audience view.',
    placeholder: 'https://slides.com/user/deck/embed',
    hostnames: ['slides.com'],
    defaultHeight: 560,
    requiresEmbedUrl: true,
  },

  // ─── CODE ────────────────────────────────────────────────────────────────────
  {
    type: 'jsfiddle',
    label: 'JSFiddle',
    categories: ['code'],
    description: 'Quick HTML, CSS, and JavaScript examples.',
    placeholder: 'https://jsfiddle.net/...',
    hostnames: ['jsfiddle.net'],
    defaultHeight: 460,
    requiresEmbedUrl: true,
    iconName: 'SiJsfiddle',
  },
  {
    type: 'codepen',
    label: 'CodePen',
    categories: ['code', 'popular'],
    description: 'Visual front-end demos and interactive pens.',
    placeholder: 'https://codepen.io/user/pen/...',
    hostnames: ['codepen.io'],
    defaultHeight: 460,
    iconName: 'SiCodepen',
  },
  {
    type: 'replit',
    label: 'Replit',
    categories: ['code'],
    description: 'Full interactive IDEs for many programming languages.',
    placeholder: 'https://replit.com/@user/repl-name',
    hostnames: ['replit.com'],
    defaultHeight: 560,
    iconName: 'SiReplit',
  },
  {
    type: 'stackblitz',
    label: 'StackBlitz',
    categories: ['code'],
    description: 'Full-stack web project sandboxes.',
    placeholder: 'https://stackblitz.com/edit/...',
    hostnames: ['stackblitz.com'],
    defaultHeight: 560,
    iconName: 'SiStackblitz',
  },
  {
    type: 'github-gist',
    label: 'GitHub Gist',
    categories: ['code'],
    description: 'Clean code snippets with syntax highlighting.',
    placeholder: 'https://gist.github.com/user/id',
    hostnames: ['gist.github.com'],
    defaultHeight: 420,
    iconName: 'SiGithub',
  },
  {
    type: 'glitch',
    label: 'Glitch',
    categories: ['code'],
    description: 'Remixable web apps and project demos.',
    placeholder: 'https://glitch.com/edit/#!/project',
    hostnames: ['glitch.com'],
    defaultHeight: 560,
    iconName: 'SiGlitch',
  },
  {
    type: 'codesnip',
    label: 'CodeSnip',
    categories: ['code'],
    description: 'Modern snippets with AI explanations.',
    placeholder: 'https://codesnip.dev/...',
    hostnames: ['codesnip.dev', 'www.codesnip.dev'],
    defaultHeight: 460,
  },
  {
    type: 'codesandbox',
    label: 'CodeSandbox',
    categories: ['code'],
    description: 'Complex front-end architectures and templates.',
    placeholder: 'https://codesandbox.io/p/sandbox/...',
    hostnames: ['codesandbox.io'],
    defaultHeight: 560,
    iconName: 'SiCodesandbox',
  },
  // NEW ↓
  {
    type: 'observable',
    label: 'Observable',
    categories: ['code'],
    description: 'Reactive data-science notebooks with live D3/Plot charts.',
    placeholder: 'https://observablehq.com/embed/@user/notebook',
    hostnames: ['observablehq.com'],
    defaultHeight: 520,
    requiresEmbedUrl: true,
    iconName: 'SiObservable',
  },
  {
    type: 'mybinder',
    label: 'MyBinder',
    categories: ['code'],
    description: 'Shareable Jupyter notebook environments from any Git repo.',
    placeholder: 'https://mybinder.org/v2/gh/user/repo/HEAD',
    hostnames: ['mybinder.org'],
    defaultHeight: 640,
    iconName: 'SiJupyter',
  },
  {
    type: 'kaggle',
    label: 'Kaggle',
    categories: ['code'],
    description: 'Public data-science notebooks and competition kernels.',
    placeholder: 'https://www.kaggle.com/embed/user/notebook',
    hostnames: ['kaggle.com', 'www.kaggle.com'],
    defaultHeight: 560,
    requiresEmbedUrl: true,
    iconName: 'SiKaggle',
  },
  {
    type: 'huggingface',
    label: 'Hugging Face',
    categories: ['code'],
    description: 'Live ML model demos and Gradio/Streamlit Spaces.',
    placeholder: 'https://huggingface.co/spaces/user/space',
    hostnames: ['huggingface.co'],
    defaultHeight: 640,
    iconName: 'SiHuggingface',
  },
  {
    type: 'wandb',
    label: 'Weights & Biases',
    categories: ['code'],
    description: 'ML experiment reports with interactive charts and metrics.',
    placeholder: 'https://api.wandb.ai/links/user/report-id',
    hostnames: ['wandb.ai', 'api.wandb.ai'],
    defaultHeight: 560,
    iconName: 'SiWeightsandbiases',
  },
  {
    type: 'gitpod',
    label: 'Gitpod',
    categories: ['code'],
    description: 'Instant cloud dev environments from any repository.',
    placeholder: 'https://gitpod.io/#https://github.com/user/repo',
    hostnames: ['gitpod.io'],
    defaultHeight: 640,
    iconName: 'SiGitpod',
  },
  {
    type: 'google-colab',
    label: 'Google Colab',
    categories: ['code', 'popular'],
    description: 'Cloud-based Jupyter notebooks for data science and AI.',
    placeholder: 'https://colab.research.google.com/drive/...',
    hostnames: ['colab.research.google.com'],
    defaultHeight: 560,
    iconName: 'SiGooglecolab',
  },

  // ─── MEDIA ───────────────────────────────────────────────────────────────────
  {
    type: 'youtube',
    label: 'YouTube',
    categories: ['media'],
    description: 'Educational videos, lectures, and screencasts.',
    placeholder: 'https://www.youtube.com/watch?v=...',
    hostnames: ['youtube.com', 'www.youtube.com', 'youtu.be'],
    defaultHeight: 420,
    allow: 'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share',
    iconName: 'SiYoutube',
  },
  {
    type: 'vimeo',
    label: 'Vimeo',
    categories: ['media'],
    description: 'High-quality hosted video and private course media.',
    placeholder: 'https://vimeo.com/...',
    hostnames: ['vimeo.com', 'www.vimeo.com', 'player.vimeo.com'],
    defaultHeight: 420,
    allow: 'autoplay; fullscreen; picture-in-picture',
    iconName: 'SiVimeo',
  },
  {
    type: 'loom',
    label: 'Loom',
    categories: ['media'],
    description: 'Recorded walkthroughs and talking-head tutorials.',
    placeholder: 'https://www.loom.com/share/...',
    hostnames: ['loom.com', 'www.loom.com'],
    defaultHeight: 420,
    iconName: 'SiLoom',
  },
  {
    type: 'google-vids',
    label: 'Google Vids',
    categories: ['media'],
    description: 'AI-assisted educational videos and slide-videos.',
    placeholder: 'https://vids.google.com/...',
    hostnames: ['vids.google.com', 'drive.google.com'],
    defaultHeight: 480,
    iconName: 'SiGoogle',
  },
  {
    type: 'wistia',
    label: 'Wistia',
    categories: ['media'],
    description: 'Course video with analytics and engagement tooling.',
    placeholder: 'https://fast.wistia.net/embed/iframe/...',
    hostnames: ['wistia.com', 'fast.wistia.net'],
    defaultHeight: 420,
    iconName: 'SiWistia',
  },
  {
    type: 'spotify',
    label: 'Spotify',
    categories: ['media'],
    description: 'Podcasts and curated study playlists.',
    placeholder: 'https://open.spotify.com/...',
    hostnames: ['open.spotify.com', 'spotify.com'],
    defaultHeight: 352,
    iconName: 'SiSpotify',
  },
  {
    type: 'soundcloud',
    label: 'SoundCloud',
    categories: ['media'],
    description: 'Audio examples, music lessons, and listening tasks.',
    placeholder: 'https://soundcloud.com/...',
    hostnames: ['soundcloud.com', 'w.soundcloud.com'],
    defaultHeight: 320,
    iconName: 'SiSoundcloud',
  },
  {
    type: 'suno',
    label: 'Suno',
    categories: ['media'],
    description: 'AI-generated songs and creative audio assignments.',
    placeholder: 'https://suno.com/song/...',
    hostnames: ['suno.com', 'www.suno.com'],
    defaultHeight: 420,
    iconName: 'SiSuno',
  },
  {
    type: 'sodaphonic',
    label: 'Sodaphonic',
    categories: ['media'],
    description: 'Browser audio editor for podcasting modules.',
    placeholder: 'https://sodaphonic.com/...',
    hostnames: ['sodaphonic.com', 'www.sodaphonic.com'],
    defaultHeight: 520,
  },
  // NEW ↓
  {
    type: 'rutube',
    label: 'RuTube',
    categories: ['media'],
    description: 'Russian state-accessible video — mirrors or supplements YouTube.',
    placeholder: 'https://rutube.ru/video/...',
    hostnames: ['rutube.ru'],
    defaultHeight: 420,
    allow: 'autoplay; fullscreen',
    iconName: 'SiRutube',
  },
  {
    type: 'vk-video',
    label: 'VK Video',
    categories: ['media'],
    description: 'VKontakte video — widely watched across Russia and Kazakhstan.',
    placeholder: 'https://vk.com/video-...',
    hostnames: ['vk.com', 'vkvideo.ru'],
    defaultHeight: 420,
    allow: 'autoplay; encrypted-media; fullscreen',
    iconName: 'SiVk',
  },
  {
    type: 'vk-clips',
    label: 'VK Clips / Posts',
    categories: ['media'],
    description: 'Short-form videos and announcements from VK.',
    placeholder: 'https://vk.com/clip-...',
    hostnames: ['vk.com'],
    defaultHeight: 560,
    iconName: 'SiVk',
  },
  {
    type: 'ted',
    label: 'TED / TEDx',
    categories: ['media'],
    description: 'Conference talks on science, design, society, and innovation.',
    placeholder: 'https://www.ted.com/talks/...',
    hostnames: ['ted.com', 'www.ted.com', 'embed.ted.com'],
    defaultHeight: 480,
    allow: 'autoplay; fullscreen',
    requiresEmbedUrl: true,
    iconName: 'SiTed',
  },
  {
    type: 'deezer',
    label: 'Deezer',
    categories: ['media'],
    description: 'Music and podcast playlists for listening comprehension tasks.',
    placeholder: 'https://www.deezer.com/playlist/...',
    hostnames: ['deezer.com', 'www.deezer.com', 'widget.deezer.com'],
    defaultHeight: 350,
    requiresEmbedUrl: true,
    iconName: 'SiDeezer',
  },
  {
    type: 'mixcloud',
    label: 'Mixcloud',
    categories: ['media'],
    description: 'Radio shows and long-form audio mixes for background listening.',
    placeholder: 'https://www.mixcloud.com/user/mix/',
    hostnames: ['mixcloud.com', 'www.mixcloud.com'],
    defaultHeight: 120,
    requiresEmbedUrl: true,
    iconName: 'SiMixcloud',
  },
  {
    type: 'panopto',
    label: 'Panopto',
    categories: ['media'],
    description: 'University lecture recordings with chapters and in-video quizzes.',
    placeholder: 'https://university.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=...',
    hostnames: ['hosted.panopto.com', 'panopto.com'],
    defaultHeight: 480,
    allow: 'autoplay; fullscreen',
    requiresEmbedUrl: true,
    iconName: 'SiPanopto',
  },
  {
    type: 'kaltura',
    label: 'Kaltura',
    categories: ['media'],
    description: 'Institutional video platform integrated with Moodle and Canvas.',
    placeholder: 'https://cdnapisec.kaltura.com/p/partner-id/embedPlaykitJs/...',
    hostnames: ['kaltura.com', 'cdnapisec.kaltura.com'],
    defaultHeight: 480,
    allow: 'autoplay; fullscreen',
    requiresEmbedUrl: true,
    iconName: 'SiKaltura',
  },

  // ─── ASSESSMENT ──────────────────────────────────────────────────────────────
  {
    type: 'h5p',
    label: 'H5P',
    categories: ['assessment'],
    description: 'Interactive LMS content such as quizzes and draft-and-drop tasks.',
    placeholder: 'https://h5p.org/h5p/embed/...',
    hostnames: ['h5p.org', 'h5p.com'],
    defaultHeight: 560,
    iconName: 'SiH5p',
  },
  {
    type: 'genially',
    label: 'Genially',
    categories: ['assessment'],
    description: 'Gamified presentations and interactive images.',
    placeholder: 'https://view.genially.com/...',
    hostnames: ['genially.com', 'view.genially.com'],
    defaultHeight: 560,
    iconName: 'SiGenially',
  },
  {
    type: 'typeform',
    label: 'Typeform',
    categories: ['assessment'],
    description: 'High-engagement surveys and entry or exit tickets.',
    placeholder: 'https://form.typeform.com/to/...',
    hostnames: ['typeform.com', 'form.typeform.com'],
    defaultHeight: 560,
    iconName: 'SiTypeform',
  },
  {
    type: 'jotform',
    label: 'Jotform',
    categories: ['assessment'],
    description: 'Forms with logic, uploads, and payment workflows.',
    placeholder: 'https://form.jotform.com/...',
    hostnames: ['jotform.com', 'form.jotform.com'],
    defaultHeight: 560,
    iconName: 'SiJotform',
  },
  {
    type: 'google-forms',
    label: 'Google Forms',
    categories: ['assessment', 'popular'],
    description: 'Quick data-driven quizzes and course surveys.',
    placeholder: 'https://docs.google.com/forms/d/e/...',
    hostnames: ['docs.google.com'],
    defaultHeight: 640,
    iconName: 'SiGoogleforms',
  },
  {
    type: 'tally',
    label: 'Tally',
    categories: ['assessment'],
    description: 'Notion-style forms that feel lightweight in lessons.',
    placeholder: 'https://tally.so/r/...',
    hostnames: ['tally.so'],
    defaultHeight: 560,
    iconName: 'SiTally',
  },
  {
    type: 'quizlet',
    label: 'Quizlet',
    categories: ['assessment'],
    description: 'Flashcard sets and study games.',
    placeholder: 'https://quizlet.com/...',
    hostnames: ['quizlet.com', 'www.quizlet.com'],
    defaultHeight: 500,
    iconName: 'SiQuizlet',
  },
  {
    type: 'kahoot',
    label: 'Kahoot!',
    categories: ['assessment', 'popular'],
    description: 'Competitive live assessments and game-based checks.',
    placeholder: 'https://create.kahoot.it/share/...',
    hostnames: ['kahoot.it', 'create.kahoot.it'],
    defaultHeight: 500,
    iconName: 'SiKahoot',
  },
  {
    type: 'mentimeter',
    label: 'Mentimeter',
    categories: ['assessment', 'popular'],
    description: 'Live polls, word clouds, and classroom feedback.',
    placeholder: 'https://www.mentimeter.com/...',
    hostnames: ['mentimeter.com', 'www.mentimeter.com'],
    defaultHeight: 560,
    iconName: 'SiMentimeter',
  },
  // NEW ↓
  {
    type: 'blooket',
    label: 'Blooket',
    categories: ['assessment'],
    description: 'Gamified quizzes and interactive learning games.',
    placeholder: 'https://www.blooket.com/play/...',
    hostnames: ['blooket.com', 'www.blooket.com'],
    defaultHeight: 500,
  },
  {
    type: 'quizizz',
    label: 'Quizizz',
    categories: ['assessment'],
    description: 'Interactive quizzes and asynchronous homework mode.',
    placeholder: 'https://quizizz.com/admin/quiz/...',
    hostnames: ['quizizz.com'],
    defaultHeight: 500,
    iconName: 'SiQuizizz',
  },
  {
    type: 'edpuzzle',
    label: 'Edpuzzle',
    categories: ['assessment'],
    description: 'Embed questions and voiceovers into any video.',
    placeholder: 'https://edpuzzle.com/embed/media/...',
    hostnames: ['edpuzzle.com'],
    defaultHeight: 500,
  },
  {
    type: 'plickers',
    label: 'Plickers',
    categories: ['assessment'],
    description: 'Low-tech classroom polling using paper cards.',
    placeholder: 'https://www.plickers.com/...',
    hostnames: ['plickers.com', 'www.plickers.com'],
    defaultHeight: 500,
  },
  {
    type: 'wooclap',
    label: 'Wooclap',
    categories: ['assessment'],
    description: 'Live audience polls, MCQs, and word clouds during lectures.',
    placeholder: 'https://app.wooclap.com/events/EVENT/questions/0',
    hostnames: ['app.wooclap.com', 'wooclap.com'],
    defaultHeight: 560,
    requiresEmbedUrl: true,
  },
  {
    type: 'slido',
    label: 'Slido',
    categories: ['assessment'],
    description: 'Real-time Q&A and polling for large university lectures.',
    placeholder: 'https://wall.sli.do/event/...',
    hostnames: ['sli.do', 'wall.sli.do', 'slido.com'],
    defaultHeight: 560,
    requiresEmbedUrl: true,
    iconName: 'SiSlido',
  },
  {
    type: 'nearpod',
    label: 'Nearpod',
    categories: ['assessment'],
    description: 'Student-paced interactive lessons with embedded assessments.',
    placeholder: 'https://nearpod.com/libraries/...',
    hostnames: ['nearpod.com'],
    defaultHeight: 580,
  },
  {
    type: 'wordwall',
    label: 'Wordwall',
    categories: ['assessment'],
    description: 'Gamified vocabulary and grammar activities — popular in CIS classrooms.',
    placeholder: 'https://wordwall.net/embed/...',
    hostnames: ['wordwall.net'],
    defaultHeight: 500,
    requiresEmbedUrl: true,
  },
  {
    type: 'poll-everywhere',
    label: 'Poll Everywhere',
    categories: ['assessment'],
    description: 'Audience-response activities with PowerPoint/Google Slides integration.',
    placeholder: 'https://www.polleverywhere.com/multiple_choice_polls/...',
    hostnames: ['polleverywhere.com', 'www.polleverywhere.com'],
    defaultHeight: 480,
    requiresEmbedUrl: true,
    iconName: 'SiPolleverywhere',
  },

  // ─── PRODUCTIVITY ────────────────────────────────────────────────────────────
  {
    type: 'airtable',
    label: 'Airtable',
    categories: ['productivity'],
    description: 'Database-driven lessons and project trackers.',
    placeholder: 'https://airtable.com/embed/...',
    hostnames: ['airtable.com'],
    defaultHeight: 560,
    iconName: 'SiAirtable',
  },
  {
    type: 'google-sheets',
    label: 'Google Sheets',
    categories: ['productivity', 'popular'],
    description: 'Live tables, datasets, and charts.',
    placeholder: 'https://docs.google.com/spreadsheets/d/...',
    hostnames: ['docs.google.com'],
    defaultHeight: 560,
    iconName: 'SiGooglesheets',
  },
  {
    type: 'trello',
    label: 'Trello',
    categories: ['productivity'],
    description: 'Project management boards and course milestones.',
    placeholder: 'https://trello.com/b/...',
    hostnames: ['trello.com'],
    defaultHeight: 560,
    iconName: 'SiTrello',
  },
  {
    type: 'notion',
    label: 'Notion',
    categories: ['productivity', 'popular'],
    description: 'Resource pages, course wikis, and structured docs.',
    placeholder: 'https://www.notion.so/...',
    hostnames: ['notion.so', 'www.notion.so'],
    defaultHeight: 560,
    iconName: 'SiNotion',
  },
  {
    type: 'coda',
    label: 'Coda',
    categories: ['productivity'],
    description: 'Interactive docs that behave like apps.',
    placeholder: 'https://coda.io/embed/...',
    hostnames: ['coda.io'],
    defaultHeight: 560,
    iconName: 'SiCoda',
  },
  {
    type: 'tableau',
    label: 'Tableau',
    categories: ['productivity'],
    description: 'Advanced analytics dashboards and data visualization.',
    placeholder: 'https://public.tableau.com/views/...',
    hostnames: ['public.tableau.com', 'tableau.com'],
    defaultHeight: 640,
    iconName: 'SiTableau',
  },
  // NEW ↓
  {
    type: 'looker-studio',
    label: 'Looker Studio',
    categories: ['productivity'],
    description: 'Google Data Studio dashboards for live research and analytics.',
    placeholder: 'https://lookerstudio.google.com/embed/reporting/...',
    hostnames: ['lookerstudio.google.com', 'datastudio.google.com'],
    defaultHeight: 640,
    requiresEmbedUrl: true,
    iconName: 'SiLooker',
  },
  {
    type: 'clickup',
    label: 'ClickUp',
    categories: ['productivity'],
    description: 'All-in-one project and task management for group coursework.',
    placeholder: 'https://app.clickup.com/...?embed=1',
    hostnames: ['app.clickup.com', 'clickup.com'],
    defaultHeight: 560,
    requiresEmbedUrl: true,
    iconName: 'SiClickup',
  },
  {
    type: 'wakelet',
    label: 'Wakelet',
    categories: ['productivity'],
    description: 'Curated collections of links, videos, and resources for a lesson.',
    placeholder: 'https://wakelet.com/wake/...',
    hostnames: ['wakelet.com'],
    defaultHeight: 560,
    iconName: 'SiWakelet',
  },
  {
    type: 'datalens',
    label: 'Yandex DataLens',
    categories: ['productivity'],
    description: 'Business intelligence and data visualization service.',
    placeholder: 'https://datalens.yandex.ru/embed/...',
    hostnames: ['datalens.yandex.ru', 'datalens.yandex.com'],
    defaultHeight: 560,
    iconName: 'SiYandex',
  },
  {
    type: 'google-docs',
    label: 'Google Docs',
    categories: ['productivity', 'popular'],
    description: 'Collaborative word processing and document editing.',
    placeholder: 'https://docs.google.com/document/d/.../edit',
    hostnames: ['docs.google.com'],
    defaultHeight: 640,
    iconName: 'SiGoogledocs',
  },

  // ─── ACADEMIC ────────────────────────────────────────────────────────────────
  {
    type: 'desmos',
    label: 'Desmos',
    categories: ['academic'],
    description: 'Interactive graphing calculator for math.',
    placeholder: 'https://www.desmos.com/calculator/...',
    hostnames: ['desmos.com', 'www.desmos.com'],
    defaultHeight: 520,
    iconName: 'SiDesmos',
  },
  {
    type: 'geogebra',
    label: 'GeoGebra',
    categories: ['academic'],
    description: 'Geometry, graphing, and 3D math simulations.',
    placeholder: 'https://www.geogebra.org/m/...',
    hostnames: ['geogebra.org', 'www.geogebra.org'],
    defaultHeight: 560,
  },
  {
    type: 'wolfram-alpha',
    label: 'Wolfram Alpha',
    categories: ['academic'],
    description: 'Computational intelligence and symbolic widgets.',
    placeholder: 'https://www.wolframalpha.com/...',
    hostnames: ['wolframalpha.com', 'www.wolframalpha.com'],
    defaultHeight: 500,
    iconName: 'SiWolframalpha',
  },
  {
    type: 'phet',
    label: 'PhET',
    categories: ['academic'],
    description: 'Science simulations for physics, chemistry, and biology.',
    placeholder: 'https://phet.colorado.edu/sims/html/...',
    hostnames: ['phet.colorado.edu'],
    defaultHeight: 620,
  },
  {
    type: 'sketchfab',
    label: 'Sketchfab',
    categories: ['academic'],
    description: 'Interactive 3D models for artifacts, anatomy, and objects.',
    placeholder: 'https://sketchfab.com/3d-models/...',
    hostnames: ['sketchfab.com', 'www.sketchfab.com'],
    defaultHeight: 520,
    allow: 'autoplay; fullscreen; xr-spatial-tracking',
    iconName: 'SiSketchfab',
  },
  {
    type: 'texlyre',
    label: 'TeXlyre',
    categories: ['academic'],
    description: 'Live LaTeX and Typst math rendering.',
    placeholder: 'https://texlyre.com/...',
    hostnames: ['texlyre.com', 'www.texlyre.com'],
    defaultHeight: 500,
  },
  // NEW ↓
  {
    type: 'yandex-maps',
    label: 'Yandex Maps',
    categories: ['academic'],
    description: 'Detailed maps and geographic context for the CIS region.',
    placeholder: 'https://yandex.ru/maps/...',
    hostnames: ['yandex.ru', 'yandex.com', 'maps.yandex.ru'],
    defaultHeight: 480,
    iconName: 'SiYandex',
  },
  {
    type: 'brilliant',
    label: 'Brilliant.org',
    categories: ['academic'],
    description: 'Interactive problem solving in math, science, and CS.',
    placeholder: 'https://brilliant.org/courses/...',
    hostnames: ['brilliant.org'],
    defaultHeight: 600,
    iconName: 'SiBrilliant',
  },
  {
    type: 'symbolab',
    label: 'Symbolab',
    categories: ['academic'],
    description: 'Step-by-step math solver and graphing calculator.',
    placeholder: 'https://www.symbolab.com/solver/...',
    hostnames: ['symbolab.com', 'www.symbolab.com'],
    defaultHeight: 600,
  },
  {
    type: 'stepik',
    label: 'Stepik',
    categories: ['academic', 'popular'],
    description: 'Leading Russian/CIS MOOC with CS, math, and science courses.',
    placeholder: 'https://stepik.org/lesson/.../step/1?unit=...',
    hostnames: ['stepik.org'],
    defaultHeight: 600,
    requiresEmbedUrl: true,
    iconName: 'SiStepik',
  },
  {
    type: 'overleaf',
    label: 'Overleaf',
    categories: ['academic'],
    description: 'Collaborative LaTeX editor for reports, theses, and papers.',
    placeholder: 'https://www.overleaf.com/read/...',
    hostnames: ['overleaf.com', 'www.overleaf.com'],
    defaultHeight: 640,
    iconName: 'SiOverleaf',
  },
  {
    type: 'molview',
    label: 'MolView',
    categories: ['academic'],
    description: 'Interactive 2D/3D molecular structure viewer for chemistry.',
    placeholder: 'https://embed.molview.org/v1/?smiles=...',
    hostnames: ['molview.org', 'embed.molview.org'],
    defaultHeight: 520,
    requiresEmbedUrl: true,
  },
  {
    type: 'google-maps',
    label: 'Google Maps',
    categories: ['academic'],
    description: 'Geographic context for history, social science, and fieldwork.',
    placeholder: 'https://www.google.com/maps/embed?pb=...',
    hostnames: ['google.com', 'www.google.com', 'maps.google.com'],
    defaultHeight: 480,
    requiresEmbedUrl: true,
    iconName: 'SiGooglemaps',
  },
  {
    type: 'chemtube3d',
    label: 'ChemTube3D',
    categories: ['academic'],
    description: 'Animated 3D reaction mechanisms for university chemistry.',
    placeholder: 'https://www.chemtube3d.com/...',
    hostnames: ['chemtube3d.com', 'www.chemtube3d.com'],
    defaultHeight: 560,
  },

  // ─── COLLABORATION ────────────────────────────────────────────────────────────
  {
    type: 'notebooklm',
    label: 'NotebookLM',
    categories: ['collaboration'],
    description: 'AI-grounded research environments for source material.',
    placeholder: 'https://notebooklm.google.com/...',
    hostnames: ['notebooklm.google.com'],
    defaultHeight: 560,
    iconName: 'SiGoogle',
  },
  {
    type: 'hyperbeam',
    label: 'Hyperbeam',
    categories: ['collaboration'],
    description: 'Shared co-browsing sessions inside a lesson.',
    placeholder: 'https://hyperbeam.com/...',
    hostnames: ['hyperbeam.com', 'www.hyperbeam.com'],
    defaultHeight: 560,
  },
  {
    type: 'discord',
    label: 'Discord',
    categories: ['collaboration', 'popular'],
    description: 'Course community invites and channel widgets.',
    placeholder: 'https://discord.com/invite/...',
    hostnames: ['discord.com', 'discord.gg'],
    defaultHeight: 420,
    iconName: 'SiDiscord',
  },
  // NEW ↓
  {
    type: 'telegram',
    label: 'Telegram Post',
    categories: ['collaboration', 'popular'],
    description: 'Embedded messages and announcements from Telegram channels.',
    placeholder: 'https://t.me/channel/123',
    hostnames: ['t.me'],
    defaultHeight: 400,
    iconName: 'SiTelegram',
  },
  {
    type: 'chatgpt',
    label: 'ChatGPT Share',
    categories: ['collaboration', 'popular'],
    description: 'Shared AI conversations and guided learning threads.',
    placeholder: 'https://chatgpt.com/share/...',
    hostnames: ['chatgpt.com', 'openai.com'],
    defaultHeight: 560,
    iconName: 'SiOpenai',
  },
  {
    type: 'padlet',
    label: 'Padlet',
    categories: ['collaboration'],
    description: 'Shared digital walls for brainstorming, portfolios, and Q&A.',
    placeholder: 'https://padlet.com/user/board',
    hostnames: ['padlet.com'],
    defaultHeight: 560,
    iconName: 'SiPadlet',
  },
  {
    type: 'flip',
    label: 'Flip',
    categories: ['collaboration'],
    description: 'Asynchronous video discussion boards for reflective assignments.',
    placeholder: 'https://flip.com/groups/...',
    hostnames: ['flip.com'],
    defaultHeight: 560,
    iconName: 'SiFlip',
  },
] as const satisfies readonly EmbedProvider[];

export type EmbedType = (typeof EMBED_PROVIDERS)[number]['type'];

export const DEFAULT_EMBED_TYPE: EmbedType = 'youtube';

const PROVIDERS_BY_TYPE = new Map<EmbedType, EmbedProvider>(
  EMBED_PROVIDERS.map((provider) => [provider.type, provider]),
);

export function getEmbedProvider(type: EmbedType | string | null | undefined): EmbedProvider | null {
  if (!type) return null;
  return PROVIDERS_BY_TYPE.get(type as EmbedType) ?? null;
}

export function isEmbedType(type: string | null | undefined): type is EmbedType {
  return Boolean(type && PROVIDERS_BY_TYPE.has(type as EmbedType));
}

/**
 * Returns providers filtered and sorted for a given category.
 * Providers without an `iconName` are sorted last so icon grids look clean.
 */
export function getProvidersByCategory(category: EmbedCategoryId): EmbedProvider[] {
  return (EMBED_PROVIDERS as readonly EmbedProvider[])
    .filter((p) => p.categories.includes(category))
    .toSorted((a, b) => {
      if (a.iconName && !b.iconName) return -1;
      if (!a.iconName && b.iconName) return 1;
      return a.label.localeCompare(b.label);
    });
}
