name: Web Image
on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'package.json'
      - 'bun.lock'
      - '.github/workflows/docker-build.yaml'
  pull_request:
    paths:
      - 'apps/web/**'
      - 'package.json'
      - 'bun.lock'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build Web Docker image
        run: docker build -f apps/web/Dockerfile -t ashyq-bilim-web .
